### PR TITLE
Add .bowerrc

### PR DESCRIPTION
**Pull request by adambutler**
Adding `.bowerrc` to prevent issues where people have different versions of bower installed.

cc/ @nouveller

### CODE REVIEW

**Comment by daviddarnes** [comment]
Is this needed? Bower version is in the package.json?

**Comment by adambutler** [comment]
Bower is a globally installed component, it will not use the one in `node_modues`.

I have bower 1.4.1 installed which defaults to install components on `app/bower_components`.

**Comment by daviddarnes** [comment]
Ok, should probably be using the one in the node modules then. I'll merge this in if it saves hassle. Cheers.

**Comment by adambutler** [comment]
Yeah thats not a thing... sad node.

**Comment by daviddarnes** [comment]
I thought it was? Or am I thinking ruby gems…

**Comment by adambutler** [comment]
Ruby gems do this, but with node you have local and global gems. Local gems aren't loaded into your `$PATH` so therefor are not available as CLI tools.

You could point to the binary directly with something like this but it's unconventional -

```sh
./node_modules/bower/bin/bower install
```

**Comment by daviddarnes** [comment]
Fair dos!

**Comment by daviddarnes** [comment]
@adambutler when did bower make this directory change?

**Comment by adambutler** [comment]
https://github.com/bower/bower/pull/435

**Comment by daviddarnes** [comment]
Lovely, gives me a nice paper trail :+1:

**Pull request merged**
